FFT_iterative: FFT_iterative.cpp
	g++ -o iterative FFT_iterative.cpp
FFT_steps: fft_steps.cpp
	g++ -o steps fft_steps.cpp
gdb_steps: fft_steps.cpp
	g++ -g -o gdb_steps fft_steps.cpp
clean:
	rm iterative steps main
